#!/bin/bash

create_symlinks() {
    cd ~

    # Get the directory in which this script lives.
    script_dir="$(dirname "$(realpath "$0")")"

    # Get a list of all files in this directory that start with a dot.
    files=$(find $script_dir -maxdepth 1 -name ".*" -type f)

    # Create a symbolic link to each file in the home directory.
    for file in $files; do
        name=$(basename $file)
        echo "Creating symlink to $name in home directory."
        rm -rf ~/$name
        ln -s $script_dir/$name ~/$name
    done

    cp -r $script_dir/script ~/script
    sudo find ~/script -type f -exec chmod +x {} \;
}

add_settings() {
    # Copy code-server config
    touch ~/.local/share/code-server/User/settings.json

    # Get the directory in which this script lives.
    script_dir="$(dirname "$(realpath "$0")")"

    cp $script_dir/settings.json ~/.local/share/code-server/User/settings.json
}

get_zsh() {
    cd ~
    # Install zsh and oh-my-zsh
    sudo apt update -y
    sudo apt install zsh -y
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
}

font_fix() {
    cd ~
    # Custom Fonts
    git clone https://github.com/tuanpham-dev/code-server-font-patch.git
    cd code-server-font-patch
    sudo ./patch.sh
}

install_extensions_vscode() {
    code --install-extension golang.go
    code --install-extension ms-python.python
    code --install-extension gulajavaministudio.mayukaithemevsc
    code --install-extension pkief.material-icon-theme
    code --install-extension HashiCorp.terraform
    code --install-extension ritwickdey.liveserver
    code --install-extension tonybaloney.vscode-pets 
    code --install-extension github.copilot
}

install_extensions_code_server() {
    cd ~
    code-server --install-extension golang.go
    code-server --install-extension ms-python.python
    code-server --install-extension gulajavaministudio.mayukaithemevsc
    code-server --install-extension pkief.material-icon-theme
    code-server --install-extension HashiCorp.terraform
    code-server --install-extension ritwickdey.liveserver
    code-server --install-extension tonybaloney.vscode-pets

    wget https://drive.google.com/uc\?id\=1QVMynh6yf_4UUESzbt46jzRLQxLAwrfu
    mv 'uc?id=1QVMynh6yf_4UUESzbt46jzRLQxLAwrfu' copilot.vsix
    code-server --install-extension copilot.vsix
    rm copilot.vsix
}

install_tools() {
    sudo curl -s -L https://github.com/SharpSet/sharpdev/releases/download/1.8/install.sh | sudo bash
    curl -sSL https://install.python-poetry.org | python3 -
}

# If code-server is installed
if command -v code-server > /dev/null 2>&1; then
    font_fix
    install_extensions_code_server
    add_settings
else
    install_extensions_vscode
fi

get_zsh
create_symlinks
install_tools
