#!/bin/bash

create_symlinks() {
    cd ~

    # Copy code-server config
    touch ~/.local/share/code-server/User/settings.json

    # Get the directory in which this script lives.
    script_dir="$(dirname "$(realpath "$0")")"

    # Get a list of all files in this directory that start with a dot.
    files=$(find $script_dir -maxdepth 1 -name ".*" -type f)

    # Create a symbolic link to each file in the home directory.
    for file in $files; do
        name=$(basename $file)
        echo "Creating symlink to $name in home directory."
        rm -rf ~/$name
        ln -s $script_dir/$name ~/$name
    done

    cp -r $script_dir/script ~/script
    cp $script_dir/settings.json ~/.local/share/code-server/User/settings.json
}

get_git_repos() {
    # Prepare Armada Repos
    mkdir -p ~/projects
    cd ~/projects

    git clone https://github.com/armadaproject/armada.git
    git clone https://github.com/armadaproject/armada-operator.git
}

get_zsh() {
    cd ~
    # Install zsh and oh-my-zsh
    sudo apt update -y
    sudo apt install zsh -y
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
}

font_fix() {
    cd ~
    # Custom Fonts
    git clone https://github.com/tuanpham-dev/code-server-font-patch.git
    cd code-server-font-patch
    sudo ./patch.sh
}

install_extensions() {
    cd ~
    # Install Extensions
    code-server --install-extension golang.go
    code-server --install-extension ms-python.python
    code-server --install-extension gulajavaministudio.mayukaithemevsc
    code-server --install-extension pkief.material-icon-theme
    code-server --install-extension github.vscode-pull-request-github

    wget https://files.mcaq.me/5x2r7.vsix
    code-server --install-extension 5x2r7.vsix
    rm 5x2r7.vsix
}

insert_envs() {
    script_dir="$(dirname "$(realpath "$0")")"

    # for each dir in script_dir, get its name, and copy it to
    # ~/projects/{folder_name}/env
    for dir in $script_dir/envs/*; do
        name=$(basename $dir)
        echo "Copying envs to $name"
        cp -r $dir/* ~/projects/$name/env

        # Also insert a .gitignore file to ignore the env folder
        echo "*" > ~/projects/$name/env/.gitignore
    done
}

install_sharpset() {
    sudo curl -s -L https://github.com/SharpSet/sharpdev/releases/download/1.7/install.sh | sudo bash
}

get_zsh
font_fix
install_extensions
get_git_repos
insert_envs
create_symlinks
install_sharpset
