# https://github.com/Sharpz7/dotfiles/blob/main/envs/k8s/sharpdev.yml

version: 1

# envfile: env/.env

scripts:
  init: |
    echo "*" > ./env/.gitignore
    echo "REPO=https://github.com/kubernetes/kubernetes.git" > ./env/.env

  jobtest: |

    # Run the command
    OUTPUT=$(CGO_ENABLED=1 make test WHAT=./pkg/controller/job KUBE_COVER=y)
    echo $OUTPUT

    # Extract the path of the HTML file from the output
    HTML_PATH=$(echo "$OUTPUT" | grep -o "/tmp/k8s_coverage/.*/combined-coverage.html")

    # Copy the HTML file to the current directory
    cp "$HTML_PATH" .

    # Inform the user
    echo "Coverage report copied to $(pwd)/combined-coverage.html"

  setup: |
    ./hack/install-etcd.sh
    export PATH="$GOPATH/src/k8s.io/kubernetes/third_party/etcd:${PATH}"
    make WHAT=cmd/kubectl
    sudo apt install net-tools

  fork: |
    ~/script/merge-upstream.sh

  verify: |
    # Pre Checks
    ./hack/update-openapi-spec.sh

    make verify
